export const cars = [
  {
    brand: "Toyota",
    model: "Camry",
    pricePerDay: 90,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "Sedan",
    discount: "10%",
    minDays: 1,
    maxDays: 30,
    discountedPrice: 80,
    wishlist: false,
    image: "./cars/toyota-camry.png",
    seats: 5,
    logo: "./logos/toyota-logo.png",
    rating: "Good",
    lastMonthRented: 12,
  },
  {
    brand: "Audi",
    model: "Q7",
    pricePerDay: 250,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    discount: "20%",
    minDays: 3,
    maxDays: 20,
    discountedPrice: 200,
    wishlist: false,
    image: "./cars/audi-q7.png",
    seats: 7,
    logo: "./logos/audi-logo.png",
    rating: "Bad",
    lastMonthRented: 3,
  },
  {
    brand: "Hyundai",
    model: "Elantra",
    pricePerDay: 70,
    fuelType: "Gasoline",
    transmission: "Manual",
    bodyType: "Sedan",
    discount: "5%",
    minDays: 1,
    maxDays: 15,
    discountedPrice: 66,
    wishlist: false,
    image: "./cars/hyundai-elantra.png",
    seats: 5,
    logo: "./logos/hyundai-logo.png",
    rating: "Good",
    lastMonthRented: 15,
  },
  {
    brand: "Mercedes-Benz",
    model: "C-Class",
    pricePerDay: 180,
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Sedan",
    discount: "18%",
    minDays: 2,
    maxDays: 25,
    discountedPrice: 148,
    wishlist: false,
    image: "./cars/Mercedes-Benz-C-Class.png",
    seats: 5,
    logo: "./logos/mercedes-logo.png",
    rating: "Good",
    lastMonthRented: 10,
  },
  {
    brand: "Nissan",
    model: "Altima",
    pricePerDay: 75,
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Sedan",
    discount: "10%",
    minDays: 1,
    maxDays: 30,
    discountedPrice: 68,
    wishlist: false,
    image: "./cars/nissan-altima.png",
    seats: 5,
    logo: "./logos/nissan-logo.png",
    rating: "Bad",
    lastMonthRented: 5,
  },
  {
    brand: "BMW",
    model: "X5",
    pricePerDay: 200,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    discount: "25%",
    minDays: 3,
    maxDays: 20,
    discountedPrice: 150,
    wishlist: false,
    image: "./cars/bmw-x5.png",
    seats: 7,
    logo: "./logos/bmw-logo.png",
    rating: "Good",
    lastMonthRented: 8,
  },
  {
    brand: "Chevrolet",
    model: "Malibu",
    pricePerDay: 85,
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Sedan",
    discount: "8%",
    minDays: 1,
    maxDays: 25,
    discountedPrice: 78,
    wishlist: false,
    image: "./cars/chevrolet-malibu.png",
    seats: 5,
    logo: "./logos/chevrolet-logo.png",
    rating: "Bad",
    lastMonthRented: 2,
  },
  {
    brand: "Ford",
    model: "F-150",
    pricePerDay: 100,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Pickup",
    discount: "12%",
    minDays: 1,
    maxDays: 10,
    discountedPrice: 88,
    wishlist: false,
    image: "./cars/ford-f-150.png",
    seats: 5,
    logo: "./logos/ford-logo.png",
    rating: "Good",
    lastMonthRented: 7,
  },
  {
    brand: "Honda",
    model: "Civic",
    pricePerDay: 80,
    fuelType: "Gasoline",
    transmission: "Manual",
    bodyType: "Sedan",
    discount: "15%",
    minDays: 2,
    maxDays: 20,
    discountedPrice: 68,
    wishlist: false,
    image: "./cars/honda-civic.png",
    seats: 5,
    logo: "./logos/honda-logo.png",
    rating: "Good",
    lastMonthRented: 13,
  },
];
