export const cars = [
  {
    id: 1,
    brand: "Toyota",
    model: "Camry",
    pricePerDay: 90,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "Sedan",
    discount: "10%",
    minDays: 1,
    maxDays: 30,
    discountedPrice: 80,
    wishlist: false,
    image: "./cars/toyota-camry.png",
    seats: 5,
    logo: "./logos/toyota-logo.png",
    rating: "Good",
    lastMonthRented: 12,
  },
  {
    id: 2,
    brand: "Audi",
    model: "Q7",
    pricePerDay: 250,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    discount: "20%",
    minDays: 3,
    maxDays: 20,
    discountedPrice: 200,
    wishlist: false,
    image: "./cars/audi-q7.png",
    seats: 7,
    logo: "./logos/audi-logo.png",
    rating: "Bad",
    lastMonthRented: 3,
  },
  {
    id: 3,
    brand: "Hyundai",
    model: "Elantra",
    pricePerDay: 70,
    fuelType: "Gasoline",
    transmission: "Manual",
    bodyType: "Sedan",
    discount: "5%",
    minDays: 1,
    maxDays: 15,
    discountedPrice: 66,
    wishlist: false,
    image: "./cars/hyundai-elantra.png",
    seats: 5,
    logo: "./logos/hyundai-logo.png",
    rating: "Good",
    lastMonthRented: 15,
  },
  {
    id: 4,
    brand: "Mercedes-Benz",
    model: "C-Class",
    pricePerDay: 180,
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Sedan",
    discount: "18%",
    minDays: 2,
    maxDays: 25,
    discountedPrice: 148,
    wishlist: false,
    image: "./cars/Mercedes-Benz-C-Class.png",
    seats: 5,
    logo: "./logos/mercedes-logo.png",
    rating: "Good",
    lastMonthRented: 10,
  },
  {
    id: 5,
    brand: "Nissan",
    model: "Altima",
    pricePerDay: 75,
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Sedan",
    discount: "10%",
    minDays: 1,
    maxDays: 30,
    discountedPrice: 68,
    wishlist: false,
    image: "./cars/nissan-altima.png",
    seats: 5,
    logo: "./logos/nissan-logo.png",
    rating: "Bad",
    lastMonthRented: 5,
  },
  {
    id: 6,
    brand: "BMW",
    model: "X5",
    pricePerDay: 200,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    discount: "25%",
    minDays: 3,
    maxDays: 20,
    discountedPrice: 150,
    wishlist: false,
    image: "./cars/bmw-x5.png",
    seats: 7,
    logo: "./logos/bmw-logo.png",
    rating: "Good",
    lastMonthRented: 8,
  },
  {
    id: 7,
    brand: "Chevrolet",
    model: "Malibu",
    pricePerDay: 85,
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Sedan",
    discount: "8%",
    minDays: 1,
    maxDays: 25,
    discountedPrice: 78,
    wishlist: false,
    image: "./cars/chevrolet-malibu.png",
    seats: 5,
    logo: "./logos/chevrolet-logo.png",
    rating: "Bad",
    lastMonthRented: 2,
  },
  {
    id: 8,
    brand: "Ford",
    model: "F-150",
    pricePerDay: 100,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Pickup",
    discount: "12%",
    minDays: 1,
    maxDays: 10,
    discountedPrice: 88,
    wishlist: false,
    image: "./cars/ford-f-150.png",
    seats: 5,
    logo: "./logos/ford-logo.png",
    rating: "Good",
    lastMonthRented: 7,
  },
  {
    id: 9,
    brand: "Honda",
    model: "Civic",
    pricePerDay: 80,
    fuelType: "Gasoline",
    transmission: "Manual",
    bodyType: "Sedan",
    discount: "15%",
    minDays: 2,
    maxDays: 20,
    discountedPrice: 68,
    wishlist: false,
    image: "./cars/honda-civic.png",
    seats: 5,
    logo: "./logos/honda-logo.png",
    rating: "Good",
    lastMonthRented: 13,
  },
];

// Tastemonilas

export const testimonials = [
  {
    feedback:
      "Booking my car was quick and easy, and the vehicle was in perfect condition. The staff was friendly and helpful throughout the process. Highly recommend!",
    name: "Sarah J.",
    location: "New York",
  },
  {
    feedback:
      "I was impressed by the wide selection of cars available. The process was seamless, and I appreciated the clean and well-maintained vehicle I received.",
    name: "John D.",
    location: "Los Angeles",
  },
  {
    feedback:
      "Great customer service! The staff went above and beyond to accommodate my last-minute booking. Will definitely use this service again.",
    name: "Emily R.",
    location: "Chicago",
  },
  {
    feedback:
      "The pricing was competitive, and the car performed beautifully on my road trip. Thanks for a hassle-free experience!",
    name: "Michael T.",
    location: "Houston",
  },
  {
    feedback:
      "Excellent service from start to finish. The online booking was straightforward, and I loved the no-hidden-fees policy.",
    name: "Linda K.",
    location: "Miami",
  },
  {
    feedback:
      "A very professional and reliable car rental company. I appreciated the quick pick-up and drop-off process.",
    name: "James P.",
    location: "San Francisco",
  },
  {
    feedback:
      "The car was spotless, and the fuel efficiency was better than I expected. Renting here made my vacation stress-free!",
    name: "Laura M.",
    location: "Orlando",
  },
  {
    feedback:
      "Affordable rates and excellent customer support. The team resolved my query promptly and ensured a smooth rental experience.",
    name: "Daniel H.",
    location: "Seattle",
  },
  {
    feedback:
      "I loved the flexibility of choosing the exact pick-up and drop-off times. Very convenient for my schedule!",
    name: "Rachel B.",
    location: "Denver",
  },
  {
    feedback:
      "The entire process was transparent, and there were no surprise charges. I will be renting from them again for my next trip.",
    name: "Chris L.",
    location: "Phoenix",
  },
  {
    feedback:
      "The car was in great condition and drove like a dream. The staff was courteous and made me feel valued as a customer.",
    name: "Olivia F.",
    location: "Atlanta",
  },
  {
    feedback:
      "Fantastic experience! The app made it so simple to book, and the support team was just a call away.",
    name: "Mark W.",
    location: "Dallas",
  },
  {
    feedback:
      "I’ve rented cars from many companies, but this one stands out for its exceptional service and well-maintained vehicles.",
    name: "Sophia G.",
    location: "Las Vegas",
  },
  {
    feedback:
      "Thank you for making my business trip so much easier! The car was reliable, and the service was outstanding.",
    name: "Ethan N.",
    location: "Boston",
  },
  {
    feedback:
      "The staff was very friendly and gave me a detailed walkthrough of the rental process. Excellent customer care!",
    name: "Anna S.",
    location: "Philadelphia",
  },
  {
    feedback:
      "I appreciated how quickly they handled my reservation. The car was ready to go as soon as I arrived. Five-star service!",
    name: "David K.",
    location: "San Diego",
  },
  {
    feedback:
      "The booking process was so smooth, and the staff ensured all my questions were answered before I drove away.",
    name: "Jessica L.",
    location: "Austin",
  },
  {
    feedback:
      "Perfect car rental experience. The vehicle was pristine, and the drop-off was a breeze. Highly recommended!",
    name: "Kevin R.",
    location: "Charlotte",
  },
  {
    feedback:
      "Very affordable rates for such top-notch service. The car felt brand new, and I loved the convenience of the entire process.",
    name: "Megan P.",
    location: "Detroit",
  },
  {
    feedback:
      "I had a minor issue with my reservation, but the team resolved it instantly. Truly excellent service!",
    name: "William C.",
    location: "San Antonio",
  },
];
